Второе домашнее задание
htmlacademy-ecmascript/489355-cinemaddict-13 pull request #4
Opened 2020-11-25 21:36 UTC by tarasovem

2020-11-27 14:48 UTC, rideorgtfo requested changes

2020-11-27 14:48 UTC, rideorgtfo commented on src/mock/film.js
> +  }
Неплохой алгоритм, но не самый оптимальный. Что если рандом всегда будет выдавать одного и того же автора?

2020-11-27 14:48 UTC, rideorgtfo commented on src/mock/film.js
> +};
Для таких случаев предлагаю сделать функцию для получения случайного значения из массива.
Это избавит от пересоздания массивов при каждом вызове функции.
Будем использовать ее так:
```
getRandomItem(titles);
getRandomItem(poster);
```

2020-11-27 14:48 UTC, rideorgtfo commented on src/mock/film.js
> +const generateCreationDate = () => {
Эту функцию обсудим на консультации

2020-11-27 14:48 UTC, rideorgtfo commented on src/mock/film.js
> +const generateDuration = () => {
Эту тоже обсудим на консультации

2020-11-27 14:48 UTC, rideorgtfo commented on src/mock/film.js
> +  const MAX_RATING = 100;
Константы лучше вынести за пределы функции.

В данном месте лучше им присвоить 1 и 10 соотвественно. А уже при расчете умножить на 10.

2020-11-27 14:48 UTC, rideorgtfo commented on src/mock/film.js
> +  }
Лучше использовать 
```
new Array(commentsCount).fill().map
```

2020-11-27 15:54 UTC, tarasovem commented on src/mock/film.js
> +  }
Переписал алгоритм через splice().

2020-11-27 16:29 UTC, tarasovem commented on src/mock/film.js
> +  }
Смотри новую реализацию с консультации

2020-11-27 16:29 UTC, tarasovem commented on src/mock/film.js
> +};
Разобрали

2020-11-27 16:30 UTC, tarasovem commented on src/mock/film.js
> +const generateDuration = () => {
Генерирую количество минут

2020-11-27 16:35 UTC, tarasovem commented on src/mock/film.js
> +  const MAX_RATING = 100;
Разобрали

2020-11-27 16:35 UTC, tarasovem commented on src/mock/film.js
> +  }
Разобрали

2020-11-28 16:51 UTC, rideorgtfo commented on src/mock/film.js
> +    });
Давай везде стараться использовать стрелочные функции

2020-11-30 09:21 UTC, rideorgtfo requested changes

2020-11-30 09:21 UTC, rideorgtfo commented on src/view/film-details.js
> +  };
Давай для передачи значений будем использовать не замыкание, а аргументы функции.
Это позволит нам ее вынести выше

2020-11-30 09:21 UTC, rideorgtfo commented on src/view/film-details.js
> +    };
dayjs

2020-11-30 09:21 UTC, rideorgtfo commented on src/view/footer-stats.js
> +    <p>${amount.toLocaleString()} movies inside</p>
Чем не угодил toString?

2020-11-30 09:21 UTC, rideorgtfo commented on src/view/menu.js
> +  }
Эти подсчеты нужно вынести за пределы вьюхи.

2020-11-30 14:15 UTC, tarasovem commented on src/view/film-card.js
> +  const yearOfCreation = new Date(creationDateTime).getFullYear();
Исправил. Теперь получаем год с помощью dayjs

2020-11-30 14:20 UTC, tarasovem commented on src/view/film-card.js
> +      <span class="film-card__genre">${genres[0]}</span>
Добавил тернарник. Если данных нет, мы просто вставляем пустую строку

2020-11-30 14:45 UTC, tarasovem commented on src/view/film-details.js
> +  const releaseDate = () => {
Нейминг исправил. Во время консультации мы договорились, что данные будут отдавать в компонент в сыром виде и там преобразовывать к тому виду, который нужен для шаблона.

2020-11-30 15:55 UTC, tarasovem commented on src/view/film-details.js
> +  };
Переименовал аргумент, чтобы было явно понятно, что это не данные из мока напрямую и функция уже вынесена за пределы шаблона

2020-11-30 16:02 UTC, tarasovem commented on src/view/footer-stats.js
> +    <p>${amount.toLocaleString()} movies inside</p>
Мне нудно отделять тысячные пробелом, поэтому применил этот метод. Если есть ещё какой-то способ будет интересно узнать =)

2020-11-30 16:25 UTC, tarasovem commented on src/view/menu.js
> +  }
Упростил подсчёты и вынес за пределы шаблона

2020-11-30 19:59 UTC, rideorgtfo commented on src/main.js
> +const mostCommentedFilmsList = new Array(FILM_COUNT).fill(undefined).map(generateFilm);
Этих фильмов нужно по 2.
В дальнейшем мы их будем вычислять из filmsList

2020-11-30 19:59 UTC, rideorgtfo commented on src/view/film-details.js
> +  return `${date} ${getMonthName(month)} ${year}`;
в dayjs уже есть функции для превращения даты в текст

2020-11-30 19:59 UTC, rideorgtfo commented on src/view/film-details.js
> +  return list.join(``);
Давай тут используем map?
```
genresList.map().join('')
```

2020-11-30 19:59 UTC, rideorgtfo commented on src/view/film-details.js
> +  };
Можно вынести выше

2020-11-30 19:59 UTC, rideorgtfo commented on src/view/film-details.js
> +  return list.join(``);
Может вынести генерацию одного комментария в отдельную функцию, принимающую комменарий?
И тут commentsList.map(getCommentTemplate)

2020-11-30 19:59 UTC, rideorgtfo commented on src/view/footer-stats.js
> +    <p>${amount.toLocaleString()} movies inside</p>
Не всегда toLocaleString будет разделять пробелом. У меня на английской версии macOS разделяется запятыми. Лучше написать свою функцию

2020-11-30 19:59 UTC, rideorgtfo commented on src/view/menu.js
> +};
Можно заменить на reduce

2020-11-30 20:08 UTC, rideorgtfo commented on src/mock/utils.js
> +  const hours = (duration - minutes) / 60;
Магические числа

2020-11-30 20:08 UTC, rideorgtfo commented on src/mock/film.js
> +    dateTime: getRandomDateTime(FIRST_FILM_DATE),
Комментарий может быть оставлен раньше, чем вышел фильм :)
Не важно, но забавно

2020-11-30 20:08 UTC, rideorgtfo commented on src/mock/utils.js
> +  return `${hours}h ${minutes}m`;
Точно хотим показывать часы, если их 0?
```
0h 23m
```

2020-12-01 06:11 UTC, tarasovem commented on src/main.js
> +const mostCommentedFilmsList = new Array(FILM_COUNT).fill(undefined).map(generateFilm);
Поменял константы для расчёта количества на EXTRA_FILM_COUNT. После копирования строк не исправил

2020-12-01 06:14 UTC, tarasovem commented on src/view/film-details.js
> +  return `${date} ${getMonthName(month)} ${year}`;
Не понимаю смысл замечания. Даже если там и есть такие методы, мы вычисляем значения и формируем строку такого вида (здесь с пробелами, а в другом месте со слешами и так далее) на основе вычисленных значений. Зачем превращать их там в строки, если они и так в строковом шаблоне преобразуются?

2020-12-01 06:31 UTC, tarasovem commented on src/view/film-details.js
> +  return list.join(``);
Переделал на map

2020-12-01 14:29 UTC, tarasovem commented on src/view/film-details.js
> +  };
Вынес и переделал формирование строки.

2020-12-01 14:37 UTC, tarasovem commented on src/view/film-details.js
> +  return list.join(``);
Переделал функцию на `.map`. Стало выглядеть намного лучше =)

2020-12-01 15:24 UTC, tarasovem commented on src/view/menu.js
> +};
В футере переделал функцию для вставки пробелов

2020-12-01 16:10 UTC, tarasovem commented on src/view/menu.js
> +};
Через reduce переписал

2020-12-01 16:18 UTC, tarasovem commented on src/mock/utils.js
> +  const hours = (duration - minutes) / 60;
Присвоил магическим числам константы

2020-12-01 16:22 UTC, tarasovem commented on src/mock/utils.js
> +  return `${hours}h ${minutes}m`;
Посмотрел на скриншот в ТЗ. Там часы не указываются. Переделал функцию.

2020-12-01 17:08 UTC, rideorgtfo requested changes

2020-12-01 17:08 UTC, rideorgtfo commented on src/view/film-details.js
> +              <button class="film-details__comment-delete">Delete</button>
```
commentsList.map(comment => `
....
...
comment.message

`)
```

2020-12-01 17:08 UTC, rideorgtfo commented on src/mock/utils.js
> +  const MINUTES_PER_HOUR = 60;
Не важно, просто для инфы
Удобнее записывать так
```
const SECOND = 1000;
const MINUTE = 60 * SECOND;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;
```

2020-12-01 18:04 UTC, merged